export const RECIPE_LIST = {
    "Fried Egg": { "Egg": 1 },
    "Omelet": { "Egg": 1, "Milk": 1 },
    "Salad": { "Leek": 1, "Dandelion": 1, "Vinegar": 1 },
    "Cheese Cauliflower": { "Cauliflower": 1, "Cheese": 1 },
    "Baked Fish": { "Sunfish": 1, "Bream": 1, "Wheat Flour": 1 },
    "Parsnip Soup": { "Parsnip": 1, "Milk": 1, "Vinegar": 1 },
    "Vegetable Medley": { "Tomato": 1, "Beet": 1 },
    "Complete Breakfast": { "Fried Egg": 1, "Milk": 1, "Hashbrowns": 1, "Pancakes": 1 },
    "Fried Calamari": { "Squid": 1, "Wheat Flour": 1, "Oil": 1 },
    "Strange Bun": { "Wheat Flour": 1, "Periwinkle": 1, "Void Mayonnaise": 1 },
    "Lucky Lunch": { "Sea Cucumber": 1, "Tortilla": 1, " Blue Jazz": 1 },
    "Fried Mushroom": { "Common Mushroom": 1, "Morel": 1, "Oil": 1 },
    "Pizza": { "Wheat Flour": 1, "Tomato": 1, "Cheese": 1 },
    "Bean Hotpot": { "Green Bean": 2 },
    "Glazed Yams": { "Yam": 1, "Sugar": 1 },
    "Carp Surprise": { "Carp": 4 },
    "Hashbrowns": { "Potato": 1, "Oil": 1 },
    "Pancakes": { "Wheat Flour": 1, "Egg": 1 },
    "Salmon Dinner": { "Salmon": 1, "Amaranth": 1, "Kale": 1 },
    "Fish Taco": { "Tuna": 1, "Tortilla": 1, "Red Cabbage": 1, "Mayonnaise": 1 },
    "Crispy Bass": { "Largemouth Bass": 1, "Wheat Flour": 1, "Oil": 1 },
    "Pepper Poppers": { "Hot Pepper": 1, "Cheese": 1 },
    "Bread": { "Wheat Flour": 1 },
    "Tom Kha Soup": { "Coconut": 1, "Shrimp": 1, "Common Mushroom": 1 },
    "Trout Soup": { "Rainbow Trout": 1, "Green Algae": 1 },
    "Chocolate Cake": { "Wheat Flour": 1, "Sugar": 1, "Egg": 1 },
    "Pink Cake": { "Melon": 1, "Wheat Flour": 1, "Sugar": 1, "Egg": 1 },
    "Rhubarb Pie": { "Rhubarb": 1, "Wheat Flour": 1, "Sugar": 1 },
    "Cookie": { "Wheat Flour": 1, "Sugar": 1, "Egg": 1 },
    "Spaghetti": { "Wheat Flour": 1, "Tomato": 1 },
    "Fried Eel": { "Eel": 1, "Oil": 1 },
    "Spicy Eel": { "Eel": 1, "Hot Pepper": 1 },
    "Sashimi": { "Any Fish": 1 },
    "Maki Roll": { "Any Fish": 1, "Seaweed": 1, "Rice": 1 },
    "Tortilla": { "Corn": 1 },
    "Red Plate": { "Red Cabbage": 1, "Radish": 1 },
    "Eggplant Parmesan": { "Eggplant": 1, "Tomato": 1 },
    "Rice Pudding": { "Milk": 1, "Sugar": 1, "Rice": 1 },
    "Ice Cream": { "Milk": 1, "Sugar": 1 },
    "Blueberry Tart": { "Blueberry": 1, "Wheat Flour": 1, "Sugar": 1, "Egg": 1 },
    "Autumn's Bounty": { "Yam": 1, "Pumpkin": 1 },
    "Pumpkin Soup": { "Pumpkin": 1, "Milk": 1 },
    "Super Meal": { "Bok Choy": 1, "Cranberries": 1, "Artichoke": 1 },
    "Cranberry Sauce": { "Cranberries": 1, "Sugar": 1 },
    "Stuffing": { "Bread": 1, "Cranberries": 1, "Hazelnut": 1 },
    "Farmer's Lunch": { "Omelet": 1, "Parsnip": 1 },
    "Survival Burger": { "Bread": 1, "Cave Carrot": 1, "Eggplant": 1 },
    "Dish O' The Sea": { "Sardine": 2, "Hashbrowns": 1 },
    "Miner's Treat": { "Cave Carrot": 2, "Sugar": 1, "Milk": 1 },
    "Roots Platter": { "Cave Carrot": 1, "Winter Root": 1 },
    "Triple Shot Espresso": { "Coffee": 3 },
    "Seafoam Pudding": { "Flounder": 1, "Midnight Carp": 1, "Squid Ink": 1 },
    "Algae Soup": { "Green Algae": 4 },
    "Pale Broth": { "White Algae": 2 },
    "Plum Pudding": { "Wild Plum": 2, "Wheat Flour": 1, "Sugar": 1 },
    "Artichoke Dip": { "Artichoke": 1, "Milk": 1 },
    "Stir Fry": { "Cave Carrot": 1, "Common Mushroom": 1, "Kale": 1, "Oil": 1 },
    "Roasted Hazelnuts": { "Hazelnut": 3 },
    "Pumpkin Pie": { "Pumpkin": 1, "Wheat Flour": 1, "Milk": 1, "Sugar": 1 },
    "Radish Salad": { "Oil": 1, "Vinegar": 1, "Radish": 1 },
    "Fruit Salad": { "Blueberry": 1, "Melon": 1, "Apricot": 1 },
    "Blackberry Cobbler": { "Blackberry": 2, "Sugar": 1, "Wheat Flour": 1 },
    "Cranberry Candy": { "Cranberries": 1, "Apple": 1, "Sugar": 1 },
    "Bruschetta": { "Bread": 1, "Oil": 1, "Tomato": 1 },
    "Coleslaw": { "Red Cabbage": 1, "Vinegar": 1, "Mayonnaise": 1 },
    "Fiddlehead Risotto": { "Oil": 1, "Fiddlehead Fern": 1, "Garlic": 1 },
    "Poppyseed Muffin": { "Poppy": 1, "Wheat Flour": 1, "Sugar": 1 },
    "Chowder": { "Clam": 1, "Milk": 1 },
    "Fish Stew": { "Crayfish": 1, "Mussel": 1, "Periwinkle": 1, "Tomato": 1 },
    "Escargot": { "Snail": 1, "Garlic": 1 },
    "Lobster Bisque": { "Lobster": 1, "Milk": 1 },
    "Maple Bar": { "Maple Syrup": 1, "Sugar": 1, "Wheat Flour": 1 },
    "Crab Cakes": { "Crab": 1, "Wheat Flour": 1, "Egg": 1, "Oil": 1 },
    "Shrimp Cocktail": { "Tomato": 1, "Shrimp": 1, "Wild Horseradish": 1 },
    "Ginger Ale": { "Ginger": 3, "Sugar": 1 },
    "Banana Pudding": { "Banana": 1, "Milk": 1, "Sugar": 1 },
    "Mango Sticky Rice": { "Mango": 1, "Coconut": 1, "Rice": 1 },
    "Poi": { "Taro Root": 4 },
    "Tropical Curry": { "Coconut": 1, "Pineapple": 1, "Hot Pepper": 1 },
    "Squid Ink Ravioli": { "Squid Ink": 1, "Wheat Flour": 1, "Tomato": 1 },
}

export const RECIPE_ID = {
    "Fried Egg": 194,
    "Omelet": 195,
    "Salad": 196,
    "Cheese Cauliflower": 197,
    "Baked Fish": 198,
    "Parsnip Soup": 199,
    "Vegetable Medley": 200,
    "Complete Breakfast": 201,
    "Strange Bun": 203,
    "Lucky Lunch": 204,
    "Fried Mushroom": 205,
    "Pizza": 206,
    "Bean Hotpot": 207, 
    "Glazed Yams": 208,
    "Carp Surprise": 209,
    "Hashbrowns": 210,
    "Pancakes": 211,
    "Salmon Dinner": 212,
    "Fish Taco": 213,
    "Crispy Bass": 214,
    "Pepper Poppers": 215,
    "Bread": 216,
    "Tom Kha Soup": 218,
    "Trout Soup": 219,
    "Chocolate Cake": 220,
    "Pink Cake": 221,
    "Rhubarb Pie": 222,
    "Cookie": 223,
    "Spaghetti": 224,
    "Fried Eel": 225,
    "Spicy Eel": 226,
    "Sashimi": 227,
    "Maki Roll": 228,
    "Tortilla": 229,
    "Red Plate": 230,
    "Eggplant Parmesan": 231,
    "Rice Pudding": 232,
    "Ice Cream": 233,
    "Blueberry Tart": 234,
    "Autumn's Bounty": 235,
    "Pumpkin Soup": 236,
    "Super Meal": 237,
    "Cranberry Sauce": 238,
    "Stuffing": 239,
    "Farmer's Lunch": 240,
    "Survival Burger": 241,
    "Dish O' The Sea": 242,
    "Miner's Treat": 243,
    "Roots Platter": 244,
    "Triple Shot Espresso": 253,
    "Seafoam Pudding": 265,
    "Algae Soup": 456,
    "Pale Broth": 457,
    "Plum Pudding": 604,
    "Artichoke Dip": 605,
    "Stir Fry": 606,
    "Roasted Hazelnuts": 607,
    "Pumpkin Pie": 608,
    "Radish Salad": 609,
    "Fruit Salad": 610,
    "Blackberry Cobbler": 611,
    "Cranberry Candy": 612,
    "Bruschetta": 618,
    "Coleslaw": 648,
    "Fiddlehead Risotto": 649,
    "Poppyseed Muffin": 651,
    "Chowder": 727,
    "Fish Stew": 728,
    "Escargot": 729,
    "Lobster Bisque": 730,
    "Maple Bar": 731,
    "Crab Cakes": 732,
    "Shrimp Cocktail": 733,
    "Ginger Ale": 903,
    "Banana Pudding": 904,
    "Mango Sticky Rice": 905,
    "Poi": 906,
    "Tropical Curry": 907,
    "Squid Ink Ravioli": 921    
}

export const ID_RECIPE = {
    "194":"Fried Egg",
    "195":"Omelet",
    "196":"Salad",
    "197":"Cheese Cauliflower",
    "198":"Baked Fish",
    "199":"Parsnip Soup",
    "200":"Vegetable Medley",
    "201":"Complete Breakfast",
    "203":"Strange Bun",
    "204":"Lucky Lunch",
    "205":"Fried Mushroom",
    "206":"Pizza",
    "207":"Bean Hotpot",
    "208":"Glazed Yams",
    "209":"Carp Surprise",
    "210":"Hashbrowns",
    "211":"Pancakes",
    "212":"Salmon Dinner",
    "213":"Fish Taco",
    "214":"Crispy Bass",
    "215":"Pepper Poppers",
    "216":"Bread",
    "218":"Tom Kha Soup",
    "219":"Trout Soup",
    "220":"Chocolate Cake",
    "221":"Pink Cake",
    "222":"Rhubarb Pie",
    "223":"Cookie",
    "224":"Spaghetti",
    "225":"Fried Eel",
    "226":"Spicy Eel",
    "227":"Sashimi",
    "228":"Maki Roll",
    "229":"Tortilla",
    "230":"Red Plate",
    "231":"Eggplant Parmesan",
    "232":"Rice Pudding",
    "233":"Ice Cream",
    "234":"Blueberry Tart",
    "235":"Autumn's Bounty",
    "236":"Pumpkin Soup",
    "237":"Super Meal",
    "238":"Cranberry Sauce",
    "239":"Stuffing",
    "240":"Farmer's Lunch",
    "241":"Survival Burger",
    "242":"Dish O' The Sea",
    "243":"Miner's Treat",
    "244":"Roots Platter",
    "253":"Triple Shot Espresso",
    "265":"Seafoam Pudding",
    "456":"Algae Soup",
    "457":"Pale Broth",
    "604":"Plum Pudding",
    "605":"Artichoke Dip",
    "606":"Stir Fry",
    "607":"Roasted Hazelnuts",
    "608":"Pumpkin Pie",
    "609":"Radish Salad",
    "610":"Fruit Salad",
    "611":"Blackberry Cobbler",
    "612":"Cranberry Candy",
    "618":"Bruschetta",
    "648":"Coleslaw",
    "649":"Fiddlehead Risotto",
    "651":"Poppyseed Muffin",
    "727":"Chowder",
    "728":"Fish Stew",
    "729":"Escargot",
    "730":"Lobster Bisque",
    "731":"Maple Bar",
    "732":"Crab Cakes",
    "733":"Shrimp Cocktail",
    "903":"Ginger Ale",
    "904":"Banana Pudding",
    "905":"Mango Sticky Rice",
    "906":"Poi",
    "907":"Tropical Curry",
    "921":"Squid Ink Ravioli"
 };